### ISSUE TITLE
should these pipes "|" be forward-slashes "/"?

### ISSUE THREAD

**Issue by brownworth** [brownworth/CommandBuddies#1]
https://github.com/brownworth/CommandBuddies/blob/4cbf412bf55edd9c44d9b3f8a8b5592337447639/bash.txt#L48

**Comment by dchardin** [comment]
Hmm.. yeah it seems i've seen a lot of different characters used as delimiters in sed commands and always thought there must be some reason for the different ones. I'm certainly not a sed expert so I had to do some investigation today... and learned something new: 

"... It's a not-so-known fact that sed can use any character as separator for the "s" command. Basically, sed takes whatever follows the "s" as the separator. Even space."

https://backreference.org/2010/02/20/using-different-delimiters-in-sed/

ALSO:

It looks like it will be important to be mindful of the kinds of quotes that are used. Single-quotes would be better so that special characters can be included in the text argument without having to escape them. I'll post some better examples.

**Comment by dchardin** [comment]
I have updated the file. Closing issue.
